run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
      - execinquery
      - exhaustruct
      - exportloopref
      - gochecknoglobals
      - gomnd
      - mnd # this is more a nuisance than a help
      - varnamelen
      # linters that need to be verified if they are useful
      - err113
      - gci
      - wsl
      - forbidigo # this must be reenabled it forbids fmt.Println atm, but we need a proper logger to work with this
      - wrapcheck # this must be reenabled at the moment error-handling is not consistent
issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test.go
      source: "." # exclude _test.go files from linting
  exclude-dirs:
    - .git
    - vendor
    - docs
    - deployments

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - codeberg.org/konterfai/konterfai
          - github.com/google
          - github.com/oklog/run
          - github.com/prometheus
          - github.com/urfave/cli
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - codeberg.org/konterfai/konterfai