version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - gochecknoglobals
    - mnd
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - codeberg.org/konterfai/konterfai
            - github.com/google
            - github.com/oklog/run
            - github.com/prometheus
            - github.com/urfave/cli
        test:
          files:
            - $test
          allow:
            - $gostd
            - codeberg.org/konterfai/konterfai
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test.go
        source: .
    paths:
      - .git
      - vendor
      - docs
      - deployments
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .git
      - vendor
      - docs
      - deployments
      - third_party$
      - builtin$
      - examples$
