run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
      - execinquery
      - exportloopref
      - gochecknoglobals
      - gomnd
issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test.go
      source: "." # exclude _test.go files from linting
  exclude-dirs:
    - .git
    - vendor
    - docs
    - deployments