package hallucinator

// Hallucination is a hallucination generated by the Hallucinator
type Hallucination struct {
	Text         string
	RequestCount int
}

// OllamaJsonRequest is the request structure for the Ollama API.
type OllamaJsonRequest struct {
	Model    string          `json:"model"`
	Messages []OllamaMessage `json:"messages"`
	Stream   bool            `json:"stream"`
	Options  OllamaOptions   `json:"options"`
}

// OllamaMessage is the message structure for the Ollama API.
type OllamaMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// OllamaOptions is the options structure for the Ollama API.
type OllamaOptions struct {
	Temperature float64 `json:"temperature"`
	Seed        int     `json:"seed"`
}

// OllamaResponse is the response structure for the Ollama API.
type OllamaResponse struct {
	Model           string        `json:"model"`
	CreatedAt       string        `json:"created_at"`
	Message         OllamaMessage `json:"message"`
	Done            bool          `json:"done"`
	DoneReason      string        `json:"done_reason"`
	TotalDuration   int           `json:"total_duration"`
	LoadDuration    int           `json:"load_duration"`
	PromptEvalCount int           `json:"prompt_eval_count"`
	EvalCount       int           `json:"eval_count"`
	EvalDuration    int           `json:"eval_duration"`
}
