package hallucinator

// Hallucination is a hallucination generated by the Hallucinator.
type Hallucination struct {
	Text         string
	Prompt       string
	RequestCount int
}

// ollamaJSONRequest is the request structure for the Ollama API.
type ollamaJSONRequest struct {
	Model    string          `json:"model"`
	Messages []ollamaMessage `json:"messages"`
	Stream   bool            `json:"stream"`
	Options  ollamaOptions   `json:"options"`
}

// ollamaMessage is the message structure for the Ollama API.
type ollamaMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// ollamaOptions is the options structure for the Ollama API.
type ollamaOptions struct {
	Temperature float64 `json:"temperature"`
	Seed        int     `json:"seed"`
}

// ollamaResponse is the response structure for the Ollama API.
type ollamaResponse struct {
	Model           string        `json:"model"`
	CreatedAt       string        `json:"created_at"` //nolint: tagliatelle
	Message         ollamaMessage `json:"message"`
	Done            bool          `json:"done"`
	DoneReason      string        `json:"done_reason"`       //nolint: tagliatelle
	TotalDuration   int           `json:"total_duration"`    //nolint: tagliatelle
	LoadDuration    int           `json:"load_duration"`     //nolint: tagliatelle
	PromptEvalCount int           `json:"prompt_eval_count"` //nolint: tagliatelle
	EvalCount       int           `json:"eval_count"`        //nolint: tagliatelle
	EvalDuration    int           `json:"eval_duration"`     //nolint: tagliatelle
}
