{
 "title": "Konterfai",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "prompts generated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "konterfai_prompts_generated_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total data fed to crawlers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "konterfai_data_fed_bytes_total / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "robots.txt violators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "konterfai_robots_txt_violators", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "requests total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "konterfai_requests_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "graphs by agant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "requests by user-agent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "targets": [
    { "expr": "konterfai_agent_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "traffic by agent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 11 },
   "targets": [
    { "expr": "konterfai_agent_traffic_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "graphs by ip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "requests by ip",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 17 },
   "targets": [
    { "expr": "konterfai_ip_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "traffic by ip",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 22 },
   "targets": [
    { "expr": "konterfai_ip_traffic_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}