when:
  branch: main
  event: [ pull_request ]

steps:
  test:
    image: golang:1.22
    commands:
      - make test

  all-arch-build:
    image: golang:1.22
    commands:
      - make all-arch-build
      - echo 'Build artifacts:'
      - ls bin/