---
when:
  - event: [ push, pull_request ]
    branch: main
  - event: tag
    ref: refs/tags/v*

steps:
  - name: all-arch-build
    image: golang:1.22
    commands:
      - make all-arch-build
      - echo 'Build artifacts:'
      - ls bin/