when:
  branch: main
  event: [ pull_request ]

steps:
  test:
    image: golang:1.22
    commands:
      - make coverage

  coverage:
    image: woodpeckerci/plugin-codecov
    settings:
      files:
        - coverage.out
      token:
        from_secret: codecov_token

  all-arch-build:
    image: golang:1.22
    commands:
      - make all-arch-build
      - echo 'Build artifacts:'
      - ls bin/